export const Tunisia = [
    {
      region: "Ariana",
      ville: [
        "Raoued",
        "Sidi thabet",
        "Ariana Centre",
        "La soukra",
        "Kalaat landlous",
        "Ettadhamen",
        "Mnihla",
        "El omrane",
        "Ariana ville",
        "Jardin el menzah 1",
        "Cité el Ghazella",
      ],
    },
    {
      region: "Béja",
      ville: [
        "Beja nord",
        "Nefza",
        "Goubellat",
        "Mejez el bab",
        "Amdoun",
        "Teboursouk",
        "Testour",
        "Thibar",
        "Beja sud",
        "ksar bardo",
      ],
    },
    {
      region: "Ben Arous",
      ville: [
        "Ezzahra",
        "Mohamadia",
        "Rades",
        "El mourouj",
        "Fouchana",
        "Hammam chatt",
        "Hammam lif",
        "Megrine",
        "Nouvelle medina",
        "Mornag",
        "Bou mhel el bassatine",
        "Ben arous Centre",
        "Ben arous EST",
      ],
    },
    {
      region: "Bizerte",
      ville: [
        "Menzel bourguiba",
        "Utique",
        "Menzel jemil",
        "Bizerte nord",
        "Bizerte sud",
        "El alia",
        "Sejnane",
        "Ghar el melh",
        "Ghezala",
        "Jarzouna",
        "Joumine",
        "Mateur",
        "Ras jebel",
        "Tinja",
        "Bizerte centre",
      ],
    },
    {
      region: "Gabès",
      ville: [
        "El metouia",
        "Gabes Centre",
        "Gabes ouest",
        "Gabes sud",
        "El hamma",
        "Nouvelle matmata",
        "Mareth",
        "Ghannouche",
        "Matmata",
        "Menzel habib",
      ],
    },
    {
      region: "Gafsa",
      ville: [
        "El ksar",
        "El mdhilla",
        "Sned",
        "Moulares",
        "Redeyef",
        "Sidi aich",
        "Gafsa sud",
        "Metlaoui",
        "Gafsa nord",
        "Belkhir",
        "El guettar",
        "centre",
      ],
    },
    {
      region: "Jendouba",
      ville: [
        "Fernana",
        "Ghardimaou",
        "Tabarka",
        "Jendouba Centre",
        "Jendouba nord",
        "Ain draham",
        "Oued mliz",
        "Bou salem",
        "Balta bou aouene",
      ],
    },
    {
      region: "Kairouan",
      ville: [
        "Sbikha",
        "Kairouan sud",
        "Oueslatia",
        "Nasrallah",
        "Kairouan nord",
        "El ala",
        "Hajeb el ayoun",
        "Chebika",
        "Haffouz",
        "Cherarda",
        "Bou hajla",
      ],
    },
    {
      region: "Kasserine",
      ville: [
        "Haidra",
        "Sbeitla",
        "Mejel bel abbes",
        "Kasserine nord",
        "El ayoun",
        "Ezzouhour",
        "Feriana",
        "Foussana",
        "Hassi el frid",
        "Jediliane",
        "Kasserine sud",
        "Sbiba",
        "Thala",
      ],
    },
    {
      region: "Kébili",
      ville: ["Souk el ahad", "Kebili sud", "Kebili nord", "Douz", "El faouar"],
    },
    {
      region: "Le kef",
      ville: [
        "Tajerouine",
        "Touiref",
        "Nebeur",
        "Sakiet sidi youssef",
        "Le sers",
        "El ksour",
        "Le kef est",
        "Dahmani",
        "Kalaat sinane",
        "Jerissa",
        "Kalaa el khasba",
        "Le kef ouest",
        "Le kef centre",
      ],
    },
    {
      region: "Mahdia",
      ville: [
        "Melloulech",
        "Sidi alouene",
        "Mahdia Centre",
        "Souassi",
        "Ouled chamakh",
        "Bou merdes",
        "Chorbane",
        "Ksour essaf",
        "Hbira",
        "La chebba",
        "El jem",
      ],
    },
    {
      region: "La manouba",
      ville: [
        "Borj el amri",
        "Jedaida",
        "Oued ellil",
        "Tebourba",
        "El battan",
        "Mannouba Centre",
        "Mornaguia",
        "Douar hicher",
      ],
    },
    {
      region: "Médenine",
      ville: [
        "Medenine sud",
        "Beni khedache",
        "Sidi makhlouf",
        "Zarzis",
        "Medenine nord",
        "Ben guerdane",
        "Houmt Souk",
        "Midoun",
        "Ajim",
        "Erriadh",
        "El Mey",
      ],
    },
    {
      region: "Monastir",
      ville: [
        "Sayada lamta bou hajar",
        "Ksibet el mediouni",
        "Ksar helal",
        "Jemmal",
        "Sahline",
        "Monastir Centre",
        "Moknine",
        "Ouerdanine",
        "Teboulba",
        "Zeramdine",
        "Bekalta",
        "Bembla",
        "Beni hassen",
      ],
    },
    {
      region: "Nabeul",
      ville: [
        "Korba",
        "Soliman",
        "Takelsa",
        "Menzel bouzelfa",
        "Menzel temime",
        "Nabeul Centre",
        "Beni khiar",
        "Beni khalled",
        "Hammamet",
        "El haouaria",
        "Kelibia",
        "Grombalia",
        "El mida",
        "Bou argoub",
        "Dar chaabane elfehri",
        "Hammam el ghezaz",
        "Hammamet nord",
        "Hammamet centre",
        "Nabeul",
      ],
    },
    {
      region: "Sfax",
      ville: [
        "El hencha",
        "Esskhira",
        "Ghraiba",
        "El amra",
        "Bir ali ben khelifa",
        "Agareb",
        "Sfax ville",
        "Sakiet eddaier",
        "Mahras",
        "Menzel chaker",
        "Sfax est",
        "Sfax sud",
        "Jebeniana",
        "Kerkenah",
        "Sakiet ezzit",
        "Sfax El Jadida",
        "Gremda",
        "Poudrière 1",
      ],
    },
    {
      region: "Sidi bouzid",
      ville: [
        "Ben oun",
        "Bir el haffey",
        "Jilma",
        "Cebbala",
        "Ouled haffouz",
        "Mezzouna",
        "Regueb",
        "Sidi bouzid ouest",
        "Souk jedid",
        "Sidi bouzid est",
        "Maknassy",
        "Menzel bouzaiene",
      ],
    },
    {
      region: "Siliana",
      ville: [
        "Siliana sud",
        "Sidi bou rouis",
        "Siliana nord",
        "Gaafour",
        "Kesra",
        "Le krib",
        "Bou arada",
        "Bargou",
        "Makthar",
        "Rohia",
        "El aroussa",
      ],
    },
    {
      region: "Sousse",
      ville: [
        "Sidi bou ali",
        "Sidi el heni",
        "Sousse jaouhara",
        "Sousse riadh",
        "Bou ficha",
        "Akouda",
        "Hammam sousse",
        "Kalaa essghira",
        "Kondar",
        "Msaken",
        "Enfidha",
        "Hergla",
        "Kalaa el kebira",
        "Sousse Centre",
        "Bab bhar",
        "Ribat",
        "kantaoui",
        "sousse ville",
        "sousse Trocadéro",
      ],
    },
    {
      region: "Tataouine",
      ville: [
        "Tataouine sud",
        "Bir lahmar",
        "Dhehiba",
        "Ghomrassen",
        "Tataouine nord",
        "Remada",
        "Smar",
      ],
    },
    {
      region: "Tozeur",
      ville: ["Degueche", "Tozeur Centre", "Hezoua", "Nefta", "Tameghza"],
    },
    {
      region: "Tunis",
      ville: [
        "El menzah",
        "El hrairia",
        "El kabbaria",
        "El kram",
        "Bab souika",
        "Carthage",
        "Cité el khadra",
        "Bab bhar",
        "La marsa",
        "Ezzouhour",
        "Jebel jelloud",
        "Sidi el bechir",
        "La goulette",
        "Le bardo",
        "El omrane",
        "El omrane superieur",
        "El ouerdia",
        "Ettahrir",
        "Sidi hassine",
        "Essijoumi",
        "La medina",
        "Centre ville",
        "El Aouina",
        "Charguia 1",
        "El Ouardia",
        "El Mourouj",
        "La soukra",
        "Ennasr",
        "El Mégrine",
        "Sidi Daoud",
        "Boumhel",
        "Ennasr 2",
        "Montplaisir",
        "Lac 2",
        "El Menzah 5",
        "El Manar 2",
        "El Manar 1",
        "El Menzah 4",
        "El Menzah 9",
        "Ain zaghouan",
        "El Menzah 6",
        "El Menzah 8",
        "Charguia 2",
        "Bab saadoun",
        "Bab mnara",
        "Bab alioua",
        "Lac 1",
        "Jardin el menzah 2",
        "El Menzah 7",
        "Gammarth",
        "Mourouj 1",
        "Cité Erriadh",
        "El menzah 1",
        "sidi bou said",
        "cité mahraéne",
        "Centre Urbain Nord",
      ],
    },
    {
      region: "Zaghouan",
      ville: [
        "Ennadhour",
        "El Fahs",
        "Bir Mcherga",
        "Zaghouan Centre",
        "Hammam Zriba",
        "Saouef",
        "Zaghouan nord",
      ],
    },
  ];